# Generated by Django 5.1.6 on 2025-02-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'topic',
                'verbose_name_plural': 'topics',
            },
        ),
        migrations.AddField(
            model_name='postsmodel',
            name='topics',
            field=models.ManyToManyField(related_name='posts', to='app_posts.topicsmodel'),
        ),
    ]
